[window]
decorations_theme_variant = "Dark"
decorations = "None"
padding = {x = 1, y = 1}
dynamic_padding = true

[font]
normal = {family = "Hack Nerd Font Mono" , style = "Regular"}
size = 12

[colors]

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]

black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.cursor]
text = "CellBackground"
cursor = "#0cf7b8"

[cursor]
style = {shape = "Block", blinking = "On"}
blink_interval = 500
thickness = 0.3

[keyboard]
bindings = [{key = "Enter", mods = "Command", action = "ToggleFullscreen"}]
