import = ["/Users/edvard/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
decorations_theme_variant = "Dark"
decorations = "Buttonless"
#opacity = 0.3
#blur = true
dynamic_padding = false 
dimensions = {columns = 150, lines = 30}

[window.padding]
x = 5
y = 1

#[window.dimensions]
#columns = 140
#lines = 30

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font]
size = 13

#[colors]
#
#[colors.primary]
#background = "#24273a"
#foreground = "#cad3f5"
#
#[colors.normal]
#black = "#494d64"
#red = "#ed8796"
#green = "#a6da95"
#yellow = "#eed49f"
#blue = "#8aadf4"
#magenta = "#f5bde6"
#cyan = "#8bd5ca"
#white = "#b8c0e0"
#
#[colors.bright]
#
#black = "#5b6078"
#red = "#ed8796"
#green = "#a6da95"
#yellow = "#eed49f"
#blue = "#8aadf4"
#magenta = "#f5bde6"
#cyan = "#8bd5ca"
#white = "#b8c0e0"

[colors.cursor]
text = "CellBackground"
cursor = "#0cf7b8"

[colors.vi_mode_cursor] 
cursor = "#5b72f2"

[cursor]
style = {shape = "Block", blinking = "On"}
blink_interval = 500
thickness = 0.2

[keyboard]
bindings = [
{key = "Enter", mods = "Command", action = "ToggleFullscreen"},
{key = ".", mods = "Command", action = "ToggleViMode"},
]
